default: &default
  encoding: utf8
  adapter: postgresql
  username: stealth
  password: 12qw
  host: localhost
  database: maps

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
